### ISSUE TITLE
Only Super Admins should be able to clear the page cache

### ISSUE THREAD

**Issue by pippercameron** [ProjectNami/projectnami-blob-cache#10]
A check needs to be added here when the installation is a multisite to bail if the user is not a super admin.

https://github.com/ProjectNami/projectnami-blob-cache/blob/87874ba1218b7f905c38dc2a4d63458ca7cc776c/project-nami-blob-cache.php#L440

The stability of the multisite could be jeopardized, otherwise.

**Comment by patrickebates** [comment]
I'm not sold on this one.  I'm involved in two multisite installations where delegating the cache clear to individual site admins was deemed a good thing due to possible delays in contacting the super admins.

Is there a way this could be made a setting of some kind?  Allow each multisite to choose how to enforce this.  Would be fine if the default was super admins only.

**Comment by pippercameron** [comment]
Allowing admins to clear the cache only works when you have a tightly controlled internal multisite without a lot of traffic. I'm fine with defaulting to super admins only, while allowing you to turn it on for all admins explicitly. It can be a big red button that says "FTLG don't press this".
