### ISSUE TITLE
Error BlobCache not working

### ISSUE THREAD

**Issue by summer600** [ProjectNami/projectnami-blob-cache#14]
I installed ProjectNami using the gallery. Then proceeded to configure the blob-cache plugin using the readme.txt included in the zip download. I followed the steps, but receive this error in the bottom of the page:

Fatal error: Uncaught exception 'WindowsAzure\Common\ServiceException' with message 'Fail:
Code: 400
Value: The value for one of the HTTP headers is not in the correct format.
details (if any): ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:a146c9ae-0001-00bf-3df9-e94db2000000
Time:2016-07-30T00:27:22.6401938Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2011-08-18</HeaderValue></Error>.' in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php:382
Stack trace:
#0 D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php(276): WindowsAzure\Common\Internal\Http\HttpClient::throwIfError(400, 'The value for o...', '\xEF\xBB\xBF<?xml versio...', Array)
#1 D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\RestProxy.php in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\Http\HttpClient.php on line 382

running on net4.6 php5.6 and 64-bits with app settings set cache container is named "cache" using debug=1 

I am not using a default storage account but have created a new blob Standard/Hot account

**Comment by patrickebates** [comment]
Thanks for mentioning you are using the new storage account types.  I suspect this means we need to update the underlying PHP SDK for blob storage.

If you want to give that a try yourself, look inside the plugin folder to find the library.  It might work to just drop the current library right in there.  At this point, I honestly don't know.

Regardless, we'll start looking into this.  Thanks for the heads up.

**Comment by patrickebates** [comment]
FYI, I had a discussion recently with someone on the Storage team about Hot vs Standard storage accounts.  From a performance standpoint, there's no difference.  Hot is not faster than Standard.

**Comment by summer600** [comment]
I also configured the app settings to point to a standard storage account and still got the same error. This was yesterday late so will test today. Now I have migrated the site content from another wordpress site to this new one in azure. Might have been a caching issue (no pun intended) with some other part of azure. I'll post an update after doing some more testing. 
And yes I was also figuring that it is mainly a marketing rename an way to make a buck. Also this new blob storage is only blob whereas the other type lets you combine other types which might be usefull.

**Comment by summer600** [comment]
I created a new storage account usng the standard type reconfigured the app settings and caching now also works. I'll add the webjobs for cleanup later. This site has very low traffic so won't be a problem.
Problem was with the new blob only storage account type.

**Comment by correinhard** [comment]
Hi! I had the same issue on one of my newer Azure App Services. Turned out the Nami Blob Cache only works with the classic deployment model of a storage account. I tried several options when recreating the needed storage account but only a classic deployment model worked. Hope you guys can fix this in the future. Now or days it's pretty much the standard to deploy Azure Resources using the Resource Manager deployment model which has a lot of benefits when like moving resources between resource groups.

**Comment by patrickebates** [comment]
To clarify, you're not able to create a Classic account using an ARM template?

**Comment by correinhard** [comment]
No I am able to create a classic storage account in ARM but I'm only getting rid of the error when using a classic model instead of a resource manager model. You get two options when creating a storage account.
![2016-09-25_14-00-58](https://cloud.githubusercontent.com/assets/22427774/18815162/8cfe9410-8328-11e6-89fc-c3bc2e91aa52.jpg)

Azure defaults to Resource Manager but when using it the error posted by summer600 turns up within the WordPress installation when, for example, creating a menu or adding a new page.

**Comment by summer600** [comment]
Oops, I see this is still open. My issue was resolved already but I simply forgot to close this case, sorry
